[package]
name = "drm-sys"
description = "Bindings to the Direct Rendering Manager API"
version = "0.0.1"
authors = ["Gustavo Branco <guster32@gmail.com>"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = { version = "0.2.120"}

[build-dependencies]
bindgen = "0.59.2"