[package]
name = "drm-ffi"
description = "Safe, low-level bindings to the Direct Rendering Manager API"
version = "0.0.1"
license = "MIT"
authors = ["Gustavo Branco <guster32@gmail.com>"]

[dependencies]
drm-sys = { path = "drm-sys", version = "0.0.1" }
nix = "^0.23.1"
